- name: Deploy edxapp
  hosts: all
  sudo: True
  gather_facts: True
  vars:
  roles:
    - aws
    - role: nginx
      nginx_sites:
      - lms
      - cms
      nginx_default_sites:
      - lms
      nginx_extra_sites: "{{ NGINX_EDXAPP_EXTRA_SITES }}"
      nginx_extra_configs: "{{ NGINX_EDXAPP_EXTRA_CONFIGS }}"
    - edxapp
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic
      when: COMMON_ENABLE_NEWRELIC
