- name: Run edxapp migrations
  hosts: all
  sudo: False
  gather_facts: False
  vars:
    db_dry_run: "--db-dry-run"
  tasks:
      # Syncdb with migrate when the migrate user is overridden in extra vars
    - name: syncdb and migrate
      shell: >
        chdir={{ edxapp_code_dir }}
        python manage.py {{ item }} syncdb --migrate --noinput --settings=aws_migrate {{ db_dry_run }}
      environment:
        DB_MIGRATION_USER: "{{ COMMON_MYSQL_MIGRATE_USER }}"
        DB_MIGRATION_PASS: "{{ COMMON_MYSQL_MIGRATE_PASS }}"
      with_items:
        - lms
        - cms
