---

# Example sandbox configuration
# for single server community
# installs

- name: Configure instance(s)
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    openid_workaround: True
    EDXAPP_LMS_NGINX_PORT: '80'
    edx_platform_version: 'master'
    EDX_ANSIBLE_DUMP_VARS: true
    CERTS_DOWNLOAD_URL: 'http://x-omics.org:18090'
    CERTS_VERIFY_URL: 'http://x-omics.org:18090'
    ora2_version: '{{ OPENEDX_RELEASE | default("master") }}'
    certs_version: '{{ OPENEDX_RELEASE | default("master") }}'
    forum_version: '{{ OPENEDX_RELEASE | default("master") }}'
    xqueue_version: '{{ OPENEDX_RELEASE | default("master") }}'
  vars_files:
    - "group_vars/x-omics"
  roles:
    - role: nginx
      nginx_sites:
      - cms
      - lms
      - forum
      - ora
      - xqueue
      - certs
      nginx_default_sites:
      - lms
    - edxlocal
    - mongo
    - { role: 'edxapp', celery_worker: True }
    - edxapp
    - demo
    - { role: 'rabbitmq', rabbitmq_ip: '127.0.0.1' }
    - oraclejdk
    - elasticsearch
    - forum
    - { role: "xqueue", update_users: True }
    - ora
    - certs
    - edx_ansible
    - role: analytics-api
      when: ANALYTICS_API_GIT_IDENTITY
